export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS';
export const UPDATE_CONNECTION_TYPE = 'UPDATE_CONNECTION_TYPE';
export const GET_BOOKS = 'GET_BOOKS'
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS'
export const GET_BOOKS_FAILED = 'GET_BOOKS_FAILED'
export const ADD_BOOKS = 'ADD_BOOKS'


